inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - 'Gemfile'
  Exclude:
    - db/schema.rb
    - 'bin/spring'
    # take this out when done
    - spec/**/**
    - db/migrate/**
